bump_version: null
lint:
  actions_ci: false
  files_exist:
    - conf/modules.config
  files_unchanged:
    - assets/sendmail_template.txt
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Harshil Patel, Moritz E. Beber and Jose Espinosa-Carrasco
  description: Pipeline to fetch metadata and raw FastQ files from public databases
  force: false
  is_nfcore: true
  name: fetchngs
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.13.0dev
update: null
